# Generated by Django 3.2.7 on 2021-09-30 09:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('publish', django.db.models.manager.Manager()),
            ],
        ),
    ]
